name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-discover-deploy:
    runs-on: ubuntu-latest
    name: Build, discover, and deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Setup Docker environment
        run: eval $(minikube -p minikube docker-env)

      - name: Build image
        run: |
          make build-image
          docker images

      - name: Deploy to Minikube
        run: kubectl apply -f deploy/deploy-minikube.yaml

      - name: Test service URLs
        run: |
          minikube service list
          minikube service discover --url
          echo "Opening the service..."
          curl "$(minikube service discover --url)/version"
